/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmTreasurePileAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmTreasurePileAddonDeed();
			}
		}

		[ Constructable ]
		public SmTreasurePileAddon()
		{
			AddComponent( new AddonComponent( 6975 ), 1, 1, 0 );


			AddComponent( new AddonComponent( 6977 ), -1, 1, 0 );

			AddComponent( new AddonComponent( 6982 ), -1, -1, 0 );

			AddComponent( new AddonComponent( 6976 ), 0, 1, 0 );

			AddComponent( new AddonComponent( 6983 ), 0, -1, 0 );

			AddComponent( new AddonComponent( 6979 ), 0, 0, 0 );

			AddComponent( new AddonComponent( 6980 ), 1, 0, 0 );

			AddComponent( new AddonComponent( 6984 ), 1, -1, 0 );

			//AddonComponent ac = null;

		}

		public SmTreasurePileAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmTreasurePileAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmTreasurePileAddon();
			}
		}

		[Constructable]
		public SmTreasurePileAddonDeed()
		{
			Name = "SmTreasurePile";
		}

		public SmTreasurePileAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}