/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SnookerTableSAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SnookerTableSAddonDeed();
			}
		}

		[ Constructable ]
		public SnookerTableSAddon()
		{
			AddComponent( new AddonComponent( 927 ), -1, -1, 5 );

			AddComponent( new AddonComponent( 925 ), 1, -1, 5 );

			AddComponent( new AddonComponent( 925 ), 2, -1, 5 );

			AddComponent( new AddonComponent( 2869 ), 1, 1, 0 );

			AddComponent( new Felt( ), 1, 1, 6 );

			AddComponent( new AddonComponent( 925 ), 1, 1, 5 );

			AddComponent( new AddonComponent( 2869 ), 1, 0, 0 );

			AddComponent( new Felt( ), 1, 0, 6 );

			AddComponent( new AddonComponent( 2869 ), 2, 0, 0 );

			AddComponent( new Felt( ), 2, 0, 6 );

			AddComponent( new AddonComponent( 926 ), 2, 0, 5 );

			AddComponent( new AddonComponent( 2869 ), 2, 1, 0 );

			AddComponent( new Felt( ), 2, 1, 6 );

			AddComponent( new AddonComponent( 924 ), 2, 1, 5 );

			AddComponent( new AddonComponent( 2869 ), 0, 1, 0 );

			AddComponent( new Felt( ), 0, 1, 6 );

			AddComponent( new AddonComponent( 925 ), 0, 1, 5 );

			AddComponent( new AddonComponent( 926 ), -1, 1, 5 );

			AddComponent( new AddonComponent( 926 ), -1, 0, 5 );

			AddComponent( new AddonComponent( 2869 ), 0, 0, 0 );

			AddComponent( new Felt( ), 0, 0, 6 );

			AddComponent( new AddonComponent( 925 ), 0, -1, 5 );

			//AddonComponent ac = null;

		}

		public SnookerTableSAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SnookerTableSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SnookerTableSAddon();
			}
		}

		[Constructable]
		public SnookerTableSAddonDeed()
		{
			Name = "SnookerTableS";
		}

		public SnookerTableSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}